### ISSUE TITLE
No Mac OSX 10.6 support

### ISSUE THREAD

**Issue by pllim** [spacetelescope/JWSTUserTraining2016#11]
*"I went to install Astroconda today, but realized that my personal laptop's, which is a Mac running os x 10.6, is not compatible with the software.  I am not sure what I should do about this situation, as I do not have access to a computer with 10.7 or later this week.  I do have ureka installed on this laptop, if that is helpful. Any advice you can provide would be incredibly helpful."*

**~~Solution:~~** Use VM. See info at #9. (Continuum dropped support for 10.6 last year. [T]ry the VirtualBox approach, assuming Oracle hasn't dropped support for it as well. -- @jhunkeler )

**Comment by pllim** [comment]
Update: _"I went to download VirtualBox, which it seems that I need in order to use the Virtual Machine....and it seems that 10.6 running on intel hardware is not supported."_

**Comment by jhunkeler** [comment]
Not much to be done then, sadly. IT may have a loaner for them to use...

**Comment by stscieisenhamer** [comment]
Seems the last version of VirtualBox supported on os x 10.6 was version 4.3. One can download older versions of VB from:

https://www.virtualbox.org/wiki/Download_Old_Builds_4_3

Get the last one there: 4.3.40  Don't know if image that Joe built will work or not, but one can try.

**Comment by jhunkeler** [comment]
The VirtualBox addons installed on the VM won't be compatible that's for sure. The user will need to reinstall/rebuild them again. This is assuming the older vbox kernel module source is still compatible with the latest CentOS 7 Linux kernel.

https://www.virtualbox.org/manual/ch04.html#idm1948

**Comment by pllim** [comment]
Does IT load laptops to visitor not employed by STScI?

**Comment by pllim** [comment]
Update: User is resorting to "listen in only" for now. (No time to pip install each package from GitHub release tags individually.)
