### ISSUE TITLE
check_env core dumps on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by pllim** [spacetelescope/JWSTUserTraining2016#21]
*I'm running bash on Ubuntu on Windows 10. I have installed astroconda without error. I have `astroconda/bin` on my PATH. Here is the output of `check_env.py`, with:*

```
./check_env.py
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)
```

*I have a feeling it would be easier and less complicated for me to install all of the needed packages myself, e.g. using `pip`.*

**Comment by jhunkeler** [comment]
I'm not sure doing it yourself is going to fix the problem.

https://github.com/Microsoft/BashOnWindows/issues/785

The fix is to turn off KMP affinity:

``` bash
export KMP_AFFINITY=disabled
```
