### ISSUE TITLE
No Windows support

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/JWSTUserTraining2016#9]
AstroConda does not support Windows.

The last DA workshop we held provided each user a virtual machine image. This helped everybody stay on the same page during the tutorials, as well as reduced the time spent by staff fiddling with individual configurations on multiple platforms. I feel like Windows users might be left in the dust for a few of the tutorials. At the moment `imexam` cannot be compiled for Windows without a great deal of hacking (and a very-very long installation of Visual Studio Express).

In case this turns out to be a problem for a few people...

Here's a link to the updated VM:
http://ssb.stsci.edu/workshops/JWST-Workshop-2016.ova (3.3GB; 10GB post-import)

Requires:
- VT-X enabled BIOS
- VirtualBox (latest)
- 2 CPU cores
- 2GB RAM
- 128MB VRAM
- 10GB HDD space

Notes:
I replaced the Ureka installation with Astroconda and cleaned up the file system a bit. The user is left with about 5.5GB of space remaining to play around with. They could add an additional virtual storage device and go from there if that's not enough.

**Comment by astrofrog** [comment]
For WIndows users, we could just recommend the normal Anaconda installation? (and there won't be too many so downloads should be ok?)

**Comment by nden** [comment]
I just tested the VM and confirmed it works. 

It's good to have it as an option.
Last year at AAS there were many people with Win laptops who had difficulties configuring Anaconda.
The VM is a nice alternative, installable with one click.

**Comment by pllim** [comment]
Does this VM work for Mac OSX 10.6? We have a participant with that OS that claims AstroConda installation is not compatible with the OS.

**Comment by stscieisenhamer** [comment]
If they can run the latest of Virtualbox, it should be fine.

**Comment by justincely** [comment]
@pllim, the user is right: OSX 10.6 is not supported by AstroConda - we spell that out in the installation instructions on the docs page.  I don't remember what exactly the issue was, but i believe we made the decision to drop support for 10.6 a while ago when it became difficult to build and metrics showed the number of 10.6 users was extremely small.

**Comment by jhunkeler** [comment]
@plim @justincely Continuum silently dropped 10.6 support last year. I only noticed because conda mysteriously stopped functioning on the old 10.6 build machine.

@astrofrog Maybe. 
If `defaults`, `astropy`, or `conda-forge` do not provide the same versions of the software as AstroConda the user could still be in for a fun  afternoon of troubleshooting.

@nden Glad to hear it works ;)
